### PR TITLE
Remove nunjucks as a dev dependency

### PR DESCRIPTION
**Pull request by zephraph**
This addresses #13. I removed nunjucks as a direct dependency and added it as a dev dependency... I also upgrade the dev dependency to 2.3.0. Should I add a nunjucks as a peerDependency?

### CODE REVIEW

**Comment by internalfx** [comment]
I say yes, It will be less of a problem moving forward because npm 3 wont install it by default.

But it will warn if it's missing, that seems very reasonable to me.

**Comment by zephraph** [comment]
If so, which version? 2.3.0 or 1.x?

**Comment by internalfx** [comment]
NPM v3+ added in node v5+

**Comment by zephraph** [comment]
I was referring to the version of nunjucks to set the peerDependency on. It's at 2.3.0 right now, but it looks like they're already trying out version 3.

**Comment by internalfx** [comment]
I think `"^2.3"` should be fine

**Pull request merged**
