### PR TITLE
Pass context to included files

### PR DESCRIPTION
**Pull request by nicolasartman**
It looks to me like the first argument to the -Tag functions is actually the full environment, so the context wasn't being passed to included templates correctly. Should be fixed and tested now.

### CODE REVIEW

**Comment by internalfx** [comment]
@zephraph LGTM

**Comment by nicolasartman** [comment]
thanks!

**Comment by zephraph** [comment]
:+1:

**Comment by nicolasartman** [comment]
@zephraph would you mind publishing a new version to npm when you get the chance? Thanks!

**Pull request merged**
