### PR TITLE
Only change indentation if it's >= tab depth of tag

### PR DESCRIPTION
**Pull request by internalfx**
This should at least not chop text if users don't have the correct tab depth. Issue #4 

Needs tests, posting this so it can be discussed.

### CODE REVIEW

**Comment by zephraph** [comment]
If you get a chance, could you add a test to verify this behavior?

**Comment by zephraph** [comment]
I tried to modify one of the existing tests to cover this case but it didn't seem to output the expected results. Will you take a look at it?

Thanks.

**Comment by internalfx** [comment]
I'll see if I can get to it today.

**Comment by internalfx** [comment]
Now being tabbed in less than the `markdown` tag acts like not being tabbed in at all.

Which fixed the test. :smile:

**Pull request merged**
