### PR TITLE
Parse markdown at same tab depth as the {% markdown %} tag itself.

### PR DESCRIPTION
**Pull request by internalfx**
This pull request sets the tab depth of the `{% markdown %}` tag as position `0` for the tab depth of the content...

```
<h1>Homepage</h1>

      {% markdown %}

      # no pre

      - no pre
      - no pre
      - no pre


            This is wrapped in <pre>

      {% endmarkdown %}

  {% markdown %}

  # no pre

  - no pre
  - no pre
  - no pre


        This is wrapped in <pre>

  {% endmarkdown %}

```

Both Markdown blocks produce the same result.

### CODE REVIEW

**Comment by zephraph** [comment]
Oh cool, I guess this'll solve #4. I'll merge this after I've tested it out a bit.

**Comment by internalfx** [comment]
Oh yeah, sorry. That's actually what I was trying to solve. Should have referenced it.

**Comment by zephraph** [comment]
Hey, could you add a test for this as well?

**Comment by internalfx** [comment]
@zephraph all good?

**Comment by zephraph** [comment]
Just merge in master and you should be good to go.

**Comment by internalfx** [comment]
@zephraph done.

Mocha was missing from the dev deps as well....

**Comment by zephraph** [comment]
Yeah, I had it in the preinstall script. This looks good, thanks for the contribution!

**Pull request merged**
