### PR TITLE
Prevents starting spaces from being stripped

### PR DESCRIPTION
**Pull request by niftylettuce**

### CODE REVIEW

**Comment by internalfx** [comment]
This _may_ be ok...

@zephraph I'm not sure if this will break existing users templates...It shouldn't if your using the library "correctly".

**Comment by zephraph** [comment]
What about the failing test?

**Comment by niftylettuce** [comment]
I'll look if I get time!

**Comment by niftylettuce** [comment]
@internalfx @zephraph Okay we have an issue here that we need to standardize.

Either people need to do it like this:

Or like this:

And we need to enforce strictly one or the other in our tests and Readme.

It's impossible to support both - why?  Because if you have variables that have indentation in them, the indentation is not preserved, it is all stripped.  Imagine you have a JSON object stored as a variable named `foo`, and it looks like this:

```json
{
  "statusCode": 401,
  "error": "Unauthorized",
  "message": "Invalid token"
} 
```

When rendered (with the old approach before this pull request was submitted):

```html
{
"statusCode": 401,
"error": "Unauthorized",
"message": "Invalid token"
} 
```

Especially with async rendered variables - the spacing in the variables when rendered is lost.

**Comment by niftylettuce** [comment]
Actually, I think the variable rendering issue is due to the parser not preserving indentation with rendered variables that have line breaks.

```js
    // Otherwise parse until the close block and move the parser to the next position
    var body = parser.parseUntilBlocks('endmarkdown'); 
```

**Comment by niftylettuce** [comment]
https://github.com/mozilla/nunjucks/issues/734

**Comment by niftylettuce** [comment]
Input:

```njk
    <div class="col-xs-12">
      {% markdown %}
      ```json
      {{ jsonWithSpaces }}
      ```
      {% endmarkdown %}
    </div>
```

Expected:

```html
    <div class="col-xs-12">
      <pre><code class="lang-json">{
      &amp;quot;baz&amp;quot;: &amp;quot;beep&amp;quot;
      }
      </code></pre>
    </div>
```

Actual:

```html
    <div class="col-xs-12">
      <pre><code class="lang-json">{
&amp;quot;baz&amp;quot;: &amp;quot;beep&amp;quot;
}
</code></pre>

    </div>
```

**Comment by zephraph** [comment]
I agree with supporting only the first, but yeah, seems like the other issue will need to be fixed first. Thanks for your work so far. Maybe we can get some traction. This has been a lingering issue for a bit.

**Comment by kmohrf** [comment]
is anyone still working on this? I’ve been using raml2html which in turn uses nunjucks and this plugin to render rest api documentation. unfortunately all my json example objects are stripped of indentation :). sooo… why strip indentation in the first place? html doesn’t care so is there any reason why it was implemented this way?

**Pull request closed without merging**
