### PR TITLE
Expand nunjucks dep/peerDep to include ^3.0.0.

### PR DESCRIPTION
**Pull request by jgerigmeyer**

### CODE REVIEW

**Comment by zephraph** [comment]
Hey, thanks for the PR! Before I merge this in I'd like to make sure Travis is running tests on the specified version.

**Comment by jgerigmeyer** [comment]
👍 Thanks!

**Comment by jgerigmeyer** [comment]
Any chance we could get a new patch release for this change?

**Comment by zephraph** [comment]
Done.

**Pull request merged**
